PROJECT(multigraph_analysis C)

CMAKE_MINIMUM_REQUIRED(VERSION 3.1.0)

FIND_PACKAGE(PkgConfig REQUIRED)

PKG_CHECK_MODULES(GLIB REQUIRED glib-2.0)

INCLUDE_DIRECTORIES(
	${CMAKE_SOURCE_DIR}/include
	${GLIB_INCLUDE_DIRS}
)

LINK_DIRECTORIES(${GLIB_LIBRARY_DIRS})

FILE(GLOB SOURCES
    "include/*.h"
    "include/*.c"
    "src/*.h"
    "src/*.c"
)

ADD_EXECUTABLE(${CMAKE_PROJECT_NAME} ${SOURCES})

TARGET_LINK_LIBRARIES(${CMAKE_PROJECT_NAME} ${GLIB_LIBRARIES})
