# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = E:\Users\amade\Documents\Programowanie\TAiO\official_repo\multigraph_analysis

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = E:\Users\amade\Documents\Programowanie\TAiO\official_repo\multigraph_analysis

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start E:\Users\amade\Documents\Programowanie\TAiO\official_repo\multigraph_analysis\CMakeFiles E:\Users\amade\Documents\Programowanie\TAiO\official_repo\multigraph_analysis\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start E:\Users\amade\Documents\Programowanie\TAiO\official_repo\multigraph_analysis\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named multigraph_analysis

# Build rule for target.
multigraph_analysis: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 multigraph_analysis
.PHONY : multigraph_analysis

# fast build rule for target.
multigraph_analysis/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\multigraph_analysis.dir\build.make CMakeFiles/multigraph_analysis.dir/build
.PHONY : multigraph_analysis/fast

include/config.obj: include/config.c.obj
.PHONY : include/config.obj

# target to build an object file
include/config.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\multigraph_analysis.dir\build.make CMakeFiles/multigraph_analysis.dir/include/config.c.obj
.PHONY : include/config.c.obj

include/config.i: include/config.c.i
.PHONY : include/config.i

# target to preprocess a source file
include/config.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\multigraph_analysis.dir\build.make CMakeFiles/multigraph_analysis.dir/include/config.c.i
.PHONY : include/config.c.i

include/config.s: include/config.c.s
.PHONY : include/config.s

# target to generate assembly for a file
include/config.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\multigraph_analysis.dir\build.make CMakeFiles/multigraph_analysis.dir/include/config.c.s
.PHONY : include/config.c.s

src/approximation_algorithm.obj: src/approximation_algorithm.c.obj
.PHONY : src/approximation_algorithm.obj

# target to build an object file
src/approximation_algorithm.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\multigraph_analysis.dir\build.make CMakeFiles/multigraph_analysis.dir/src/approximation_algorithm.c.obj
.PHONY : src/approximation_algorithm.c.obj

src/approximation_algorithm.i: src/approximation_algorithm.c.i
.PHONY : src/approximation_algorithm.i

# target to preprocess a source file
src/approximation_algorithm.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\multigraph_analysis.dir\build.make CMakeFiles/multigraph_analysis.dir/src/approximation_algorithm.c.i
.PHONY : src/approximation_algorithm.c.i

src/approximation_algorithm.s: src/approximation_algorithm.c.s
.PHONY : src/approximation_algorithm.s

# target to generate assembly for a file
src/approximation_algorithm.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\multigraph_analysis.dir\build.make CMakeFiles/multigraph_analysis.dir/src/approximation_algorithm.c.s
.PHONY : src/approximation_algorithm.c.s

src/graph.obj: src/graph.c.obj
.PHONY : src/graph.obj

# target to build an object file
src/graph.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\multigraph_analysis.dir\build.make CMakeFiles/multigraph_analysis.dir/src/graph.c.obj
.PHONY : src/graph.c.obj

src/graph.i: src/graph.c.i
.PHONY : src/graph.i

# target to preprocess a source file
src/graph.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\multigraph_analysis.dir\build.make CMakeFiles/multigraph_analysis.dir/src/graph.c.i
.PHONY : src/graph.c.i

src/graph.s: src/graph.c.s
.PHONY : src/graph.s

# target to generate assembly for a file
src/graph.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\multigraph_analysis.dir\build.make CMakeFiles/multigraph_analysis.dir/src/graph.c.s
.PHONY : src/graph.c.s

src/graph_algorithm.obj: src/graph_algorithm.c.obj
.PHONY : src/graph_algorithm.obj

# target to build an object file
src/graph_algorithm.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\multigraph_analysis.dir\build.make CMakeFiles/multigraph_analysis.dir/src/graph_algorithm.c.obj
.PHONY : src/graph_algorithm.c.obj

src/graph_algorithm.i: src/graph_algorithm.c.i
.PHONY : src/graph_algorithm.i

# target to preprocess a source file
src/graph_algorithm.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\multigraph_analysis.dir\build.make CMakeFiles/multigraph_analysis.dir/src/graph_algorithm.c.i
.PHONY : src/graph_algorithm.c.i

src/graph_algorithm.s: src/graph_algorithm.c.s
.PHONY : src/graph_algorithm.s

# target to generate assembly for a file
src/graph_algorithm.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\multigraph_analysis.dir\build.make CMakeFiles/multigraph_analysis.dir/src/graph_algorithm.c.s
.PHONY : src/graph_algorithm.c.s

src/graph_factory.obj: src/graph_factory.c.obj
.PHONY : src/graph_factory.obj

# target to build an object file
src/graph_factory.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\multigraph_analysis.dir\build.make CMakeFiles/multigraph_analysis.dir/src/graph_factory.c.obj
.PHONY : src/graph_factory.c.obj

src/graph_factory.i: src/graph_factory.c.i
.PHONY : src/graph_factory.i

# target to preprocess a source file
src/graph_factory.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\multigraph_analysis.dir\build.make CMakeFiles/multigraph_analysis.dir/src/graph_factory.c.i
.PHONY : src/graph_factory.c.i

src/graph_factory.s: src/graph_factory.c.s
.PHONY : src/graph_factory.s

# target to generate assembly for a file
src/graph_factory.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\multigraph_analysis.dir\build.make CMakeFiles/multigraph_analysis.dir/src/graph_factory.c.s
.PHONY : src/graph_factory.c.s

src/main.obj: src/main.c.obj
.PHONY : src/main.obj

# target to build an object file
src/main.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\multigraph_analysis.dir\build.make CMakeFiles/multigraph_analysis.dir/src/main.c.obj
.PHONY : src/main.c.obj

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\multigraph_analysis.dir\build.make CMakeFiles/multigraph_analysis.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\multigraph_analysis.dir\build.make CMakeFiles/multigraph_analysis.dir/src/main.c.s
.PHONY : src/main.c.s

src/utils.obj: src/utils.c.obj
.PHONY : src/utils.obj

# target to build an object file
src/utils.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\multigraph_analysis.dir\build.make CMakeFiles/multigraph_analysis.dir/src/utils.c.obj
.PHONY : src/utils.c.obj

src/utils.i: src/utils.c.i
.PHONY : src/utils.i

# target to preprocess a source file
src/utils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\multigraph_analysis.dir\build.make CMakeFiles/multigraph_analysis.dir/src/utils.c.i
.PHONY : src/utils.c.i

src/utils.s: src/utils.c.s
.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\multigraph_analysis.dir\build.make CMakeFiles/multigraph_analysis.dir/src/utils.c.s
.PHONY : src/utils.c.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... multigraph_analysis
	@echo ... include/config.obj
	@echo ... include/config.i
	@echo ... include/config.s
	@echo ... src/approximation_algorithm.obj
	@echo ... src/approximation_algorithm.i
	@echo ... src/approximation_algorithm.s
	@echo ... src/graph.obj
	@echo ... src/graph.i
	@echo ... src/graph.s
	@echo ... src/graph_algorithm.obj
	@echo ... src/graph_algorithm.i
	@echo ... src/graph_algorithm.s
	@echo ... src/graph_factory.obj
	@echo ... src/graph_factory.i
	@echo ... src/graph_factory.s
	@echo ... src/main.obj
	@echo ... src/main.i
	@echo ... src/main.s
	@echo ... src/utils.obj
	@echo ... src/utils.i
	@echo ... src/utils.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

