name: C Build and Static Analysis

on:
  push:
    branches:
      - 'dev*'
      - 'master*'
  pull_request:
    branches:
      - 'dev*'
      - 'master*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y clang-tidy cppcheck make gcc libglib2.0-dev

      - name: Build with Makefile
        run: make

      - name: Run clang-tidy
        run: |
          clang-tidy src/*.c -- -Iinclude -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include

      - name: Run cppcheck
        run: cppcheck --enable=all --inconclusive --std=c99 src/

      - name: Clean up
        run: make clean
